spring.application.name=ceptu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.default_storage=STRING
security.jwt.secret=${JWT_SECRETS}
security.jwt.expiration-seconds=3600