spring.application.name=ceptu
spring.datasource.url=jdbc:postgresql://localhost:5432/ceptu
spring.datasource.username=postgres
spring.datasource.password=5fw}w82mO>O4x1!HUPB9RqZ197wP_shh
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.descriptor.java.EnumJavaTypeDescriptor.default_storage=STRING
security.jwt.secret=${JWT_SECRETS:Sup3r_llave_S3cr3t4_c3ptu_s3cur1ty}
security.jwt.expiration-seconds=3600